// USER ACTIONS
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_START = 'USER_AUTH_START';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';

export const USER_GEO_LOCATION = 'USER_GEO_LOCATION';
// END USER ACTIONS

// APP ACTIONS
export const APP_SPLASH_LOADING_START = 'APP_SPLASH_LOADING_START';
export const APP_SPLASH_LOADING_END = 'APP_SPLASH_LOADING_END';
// END APP ACTIONS

// NEWS ACTIONS
export const FETCH_NEWS_START = 'FETCH_NEWS_START';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAIL = 'FETCH_NEWS_FAIL';
// END NEWS ACTIONS
