// USER ACTIONS
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_START = 'USER_AUTH_START';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_AUTH_LOGOUT = 'USER_AUTH_LOGOUT';

export const USER_GEO_LOCATION = 'USER_GEO_LOCATION';

export const USER_AUTH_RESET_ERROR_STATE = 'USER_AUTH_RESET_ERROR_STATE';
// END USER ACTIONS

// APP ACTIONS
export const APP_SPLASH_LOADING_START = 'APP_SPLASH_LOADING_START';
export const APP_SPLASH_LOADING_END = 'APP_SPLASH_LOADING_END';
// END APP ACTIONS

// NEWS ACTIONS
export const FETCH_NEWS_START = 'FETCH_NEWS_START';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAIL = 'FETCH_NEWS_FAIL';

export const RESET_NEWS_STATE = 'RESET_NEWS_STATE';
// END NEWS ACTIONS

// SERVICE PROVIDER ACTIONS
export const FETCH_PROVIDER_START = 'FETCH_PROVIDER_START';
export const FETCH_PROVIDER_SUCCESS = 'FETCH_PROVIDER_SUCCESS';
export const FETCH_PROVIDER_FAIL = 'FETCH_PROVIDER_FAIL';

export const RESET_PROVIDER_STATE = 'RESET_PROVIDER_STATE';
// END SERVICE PROVIDER ACTIONS
